import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
    subsets: ['latin'],
    variable: '--font-inter',
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    let isLoggedIn = true;
    return (
        <html lang='en'>
            <body className={`${inter.className} text-gray-600`}>
                <section>{children}</section>
            </body>
        </html>
    );
}
